Document: ptmax
Title: Debian ptmax Manual
Author: <insert document author here>
Abstract: This manual describes what ptmax is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ptmax/ptmax.sgml.gz

Format: postscript
Files: /usr/share/doc/ptmax/ptmax.ps.gz

Format: text
Files: /usr/share/doc/ptmax/ptmax.text.gz

Format: HTML
Index: /usr/share/doc/ptmax/html/index.html
Files: /usr/share/doc/ptmax/html/*.html
